AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/BlockLength:
  Enabled: false
