version: '3'
services:
  db:
    image: postgres:10

  backend: &backend
    build: docker/backend
    volumes:
      - .:/app
      - ./vendor/bundle:/usr/local/bundle
    links:
      - db
      - tor
    ports:
      - 3000:3000
    env_file:
      - docker/backend/development.env
      - .env

  test:
    <<: *backend
    command: ["bundle", "exec", "guard"]
    ports: []
    env_file:
      - docker/backend/test.env
      - .env

  tor:
    image: dperson/torproxy
